<a href="https://colab.research.google.com/github/sisifo3/P_T_3/blob/main/data_csv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd


In [ ]:
# import pandas as pd
import pandas as pd
 
# Calling DataFrame constructor
df = pd.DataFrame()
 
print(df)

Empty DataFrame
Columns: []
Index: []


In [ ]:
'Atelectasis': 4198, 'Hernia': 62, 'Mass': 2291, 'No Finding': 10000, 'Fibrosis': 459, 'Infiltration': 7982, 'Effusion': 4493, 'Consolidation': 1397, 'Nodule': 2510, 'Pneumothorax': 1355, 'Edema': 736, 'Emphysema': 661, 'Cardiomegaly': 844, 'Pleural_Thickening': 1153, 'Pneumonia': 455}

In [ ]:
# Python code demonstrate creating
# DataFrame from dict narray / lists
# By default addresses.
 
import pandas as pd
 
# initialise data of lists.
data = {'path':['CheXpert-v1.0-small/train/patient00001/study1/view1_frontal.jpg','image/00000001_000.png'],'No Finding':[1,0], 'Enlarged Cardiomediastinum':[0,0], 'Cardiomegaly':[0,1] ,
                    'Lung Opacity':[0,0], 'Lung Lesion':[0,0], 'Edema':[0,0],  'Consolidation':[0,0],
                    'Pneumonia':[0,0], 'Atelectasis':[0,0] ,'Pneumothorax':[0,0], 'Pleural Effusion':[0,0],
                    'Pleural Other':[0,0], 'Fracture':[0,0], 'Support Devices':[1,0],'Hernia':[0,0],'Mass':[0,0],
                    'Fibrosis':[0,0],'Infiltration':[0,0],'Effusion':[0,0],'Nodule':[0,0],'Emphysema':[0,0],'Pleural_Thickening':[0,0]}
 
# Create DataFrame
df = pd.DataFrame(data)
 
# Print the output.
df.head()

path  ...  Pleural_Thickening
0  CheXpert-v1.0-small/train/patient00001/study1/...  ...                   0
1                             image/00000001_000.png  ...                   0

[2 rows x 23 columns]

In [ ]:
df.to_csv('Conceptual_data.csv')

In [ ]:
import random
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from PIL import Image

from torchvision import transforms

import torch
from torch.utils.data import Dataset

def getImagesLabels(filename):
    df = pd.read_csv(filename)

    relevant_cols = ['Path', 'No Finding', 'Enlarged Cardiomediastinum', 'Cardiomegaly' ,
                 'Lung Opacity', 'Lung Lesion', 'Edema',  'Consolidation',
                 'Pneumonia', 'Atelectasis' ,'Pneumothorax', 'Pleural Effusion',
                 'Pleural Other', 'Fracture', 'Support Devices']

    df = df[relevant_cols]
    df = df.replace(np.nan, 0.0)

    df = df.replace(-1.0, 2.0)


    X = df['Path']
    y = df[['No Finding', 'Enlarged Cardiomediastinum', 'Cardiomegaly' ,
                    'Lung Opacity', 'Lung Lesion', 'Edema',  'Consolidation',
                    'Pneumonia', 'Atelectasis' ,'Pneumothorax', 'Pleural Effusion',
                    'Pleural Other', 'Fracture', 'Support Devices']]
  
    return np.asarray(X), np.asarray(y)



In [ ]:
filename = '/content/drive/MyDrive/train.csv'
x1, y1 = getImagesLabels(filename)
print(y1[0])

[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]


In [ ]:
import numpy
val2 = [0,0,0,0,0,0,0,0]
val2 = [float(item) for item in val2]
val2 = numpy.array(val2)
#print(val2)
val3 = [0]*22
val3 = [float(item) for item in val3]
val3 = numpy.array(val3)
#print(val3)

for val in y1:
  val4 =np.append(val,val2)
  val3 = np.vstack([val3, val4])
  #np.vstack(dat_list)
  #val3 = numpy.append(val3, val4)
  
print(val3)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 2. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


In [ ]:
DF = pd.DataFrame(val3)

In [ ]:
DF.to_csv('y_label_data.csv')

In [ ]:
DF.head()

0    1    2    3    4    5    6   ...   15   16   17   18   19   20   21
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  2.0  1.0  0.0  2.0  2.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0  0.0  2.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4  0.0  0.0  0.0  1.0  0.0  0.0  2.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0

[5 rows x 22 columns]

In [ ]:
for val in DF:
  print(val)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21


In [ ]:
DF.columns = ['No Finding', 'Enlarged Cardiomediastinum', 'Cardiomegaly',
                    'Lung Opacity', 'Lung Lesion', 'Edema',  'Consolidation',
                    'Pneumonia', 'Atelectasis','Pneumothorax', 'Pleural Effusion',
                    'Pleural Other', 'Fracture', 'Support Devices','Hernia','Mass',
                    'Fibrosis','Infiltration','Effusion','Nodule','Emphysema','Pleural_Thickening']


In [ ]:
DF.head()

No Finding  Enlarged Cardiomediastinum  ...  Emphysema  Pleural_Thickening
0         0.0                         0.0  ...        0.0                 0.0
1         1.0                         0.0  ...        0.0                 0.0
2         0.0                         0.0  ...        0.0                 0.0
3         0.0                         0.0  ...        0.0                 0.0
4         0.0                         0.0  ...        0.0                 0.0

[5 rows x 22 columns]

In [ ]:
DF.to_csv('y_label_names_data.csv')

In [ ]:
DF =DF.drop([0])

In [ ]:
DF.head()

No Finding  Enlarged Cardiomediastinum  ...  Emphysema  Pleural_Thickening
1         1.0                         0.0  ...        0.0                 0.0
2         0.0                         0.0  ...        0.0                 0.0
3         0.0                         0.0  ...        0.0                 0.0
4         0.0                         0.0  ...        0.0                 0.0
5         0.0                         0.0  ...        0.0                 0.0

[5 rows x 22 columns]

In [ ]:
DF.insert(0, 'path', x1)

In [ ]:
DF.head()

path  ...  Pleural_Thickening
1  CheXpert-v1.0-small/train/patient00001/study1/...  ...                 0.0
2  CheXpert-v1.0-small/train/patient00002/study2/...  ...                 0.0
3  CheXpert-v1.0-small/train/patient00002/study1/...  ...                 0.0
4  CheXpert-v1.0-small/train/patient00002/study1/...  ...                 0.0
5  CheXpert-v1.0-small/train/patient00003/study1/...  ...                 0.0

[5 rows x 23 columns]

In [ ]:
DF.to_csv('y_label_names_path_data.csv')

In [ ]:
filename = '/content/drive/MyDrive/NIH_Dataset_total/Data_Entry_2017_v2020.csv'
df = pd.read_csv(filename)
df.head()

Image Index          Finding Labels  ...  OriginalImagePixelSpacing[x     y]
0  00000001_000.png            Cardiomegaly  ...                        0.143  0.143
1  00000001_001.png  Cardiomegaly|Emphysema  ...                        0.143  0.143
2  00000001_002.png   Cardiomegaly|Effusion  ...                        0.168  0.168
3  00000002_000.png              No Finding  ...                        0.171  0.171
4  00000003_001.png                  Hernia  ...                        0.168  0.168

[5 rows x 11 columns]

In [ ]:
lb = df['Finding Labels']
#print(lb)


for val in lb[0:10]:
  #print(val)
  labels = str.split(val, '|')
  print(labels)

['Cardiomegaly']
['Cardiomegaly', 'Emphysema']
['Cardiomegaly', 'Effusion']
['No Finding']
['Hernia']
['Hernia']
['Hernia', 'Infiltration']
['Hernia']
['Hernia']
['Hernia']


In [ ]:
Total_columns = ['No Finding', 'Enlarged Cardiomediastinum', 'Cardiomegaly',
                    'Lung Opacity', 'Lung Lesion', 'Edema',  'Consolidation',
                    'Pneumonia', 'Atelectasis','Pneumothorax', 'Pleural Effusion',
                    'Pleural Other', 'Fracture', 'Support Devices','Hernia','Mass',
                    'Fibrosis','Infiltration','Effusion','Nodule','Emphysema','Pleural_Thickening']

In [ ]:
index_of_A_3= np.where(Total_columns == labels)[0]
print(index_of_A_3)

[]


In [ ]:
Total_columns = ['No Finding', 'Enlarged Cardiomediastinum', 'Cardiomegaly',
                    'Lung Opacity', 'Lung Lesion', 'Edema',  'Consolidation',
                    'Pneumonia', 'Atelectasis','Pneumothorax', 'Pleural Effusion',
                    'Pleural Other', 'Fracture', 'Support Devices','Hernia','Mass',
                    'Fibrosis','Infiltration','Effusion','Nodule','Emphysema','Pleural_Thickening']


val3 = [0]*22
val3 = [float(item) for item in val3]
val3 = numpy.array(val3)



val2 = [0]* 22
val2 = [float(item) for item in val2]
val2 = numpy.array(val2)


lb = df['Finding Labels']
#print(lb)


for val in lb:
  val2 = [0]* 22
  val2 = [float(item) for item in val2]
  val2 = numpy.array(val2)
  labels = str.split(val, '|')
  index_of_A_3 = [i for i in range(len(Total_columns)) if Total_columns[i] in labels]
  for val in index_of_A_3:
    val2[val] = 1

  val3 = np.vstack([val3, val2])


print(index_of_A_3)
print(val3)

[0]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 1. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


In [ ]:
DF = pd.DataFrame(val3)

In [ ]:
DF.head()

0    1    2    3    4    5    6   ...   15   16   17   18   19   20   21
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  1.0  0.0
3  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  1.0  0.0  0.0  0.0
4  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0

[5 rows x 22 columns]

In [ ]:
DF =DF.drop([0])

In [ ]:
DF.head()

0    1    2    3    4    5    6   ...   15   16   17   18   19   20   21
1  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  1.0  0.0
3  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  1.0  0.0  0.0  0.0
4  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
5  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0

[5 rows x 22 columns]

In [ ]:
DF.to_csv('y_label_data_NIH.csv')

In [ ]:
DF.columns = ['No Finding', 'Enlarged Cardiomediastinum', 'Cardiomegaly',
                    'Lung Opacity', 'Lung Lesion', 'Edema',  'Consolidation',
                    'Pneumonia', 'Atelectasis','Pneumothorax', 'Pleural Effusion',
                    'Pleural Other', 'Fracture', 'Support Devices','Hernia','Mass',
                    'Fibrosis','Infiltration','Effusion','Nodule','Emphysema','Pleural_Thickening']


In [ ]:
DF.head()

No Finding  Enlarged Cardiomediastinum  ...  Emphysema  Pleural_Thickening
1         0.0                         0.0  ...        0.0                 0.0
2         0.0                         0.0  ...        1.0                 0.0
3         0.0                         0.0  ...        0.0                 0.0
4         1.0                         0.0  ...        0.0                 0.0
5         0.0                         0.0  ...        0.0                 0.0

[5 rows x 22 columns]

In [ ]:
DF.to_csv('y_label_names_data_NIH.csv')

In [ ]:
path = df['Image Index']

In [ ]:
DF.insert(0, 'path', path)

In [ ]:
DF.head()

path  No Finding  ...  Emphysema  Pleural_Thickening
1  00000001_001.png         0.0  ...        0.0                 0.0
2  00000001_002.png         0.0  ...        1.0                 0.0
3  00000002_000.png         0.0  ...        0.0                 0.0
4  00000003_001.png         1.0  ...        0.0                 0.0
5  00000003_002.png         0.0  ...        0.0                 0.0

[5 rows x 23 columns]

In [ ]:
DF.to_csv('y_label_names_path_data_NIH.csv')

In [ ]:
filename = '/content/y_label_names_path_data.csv'
df = pd.read_csv(filename)
filename2 = '/content/y_label_names_path_data_NIH.csv'
df2 = pd.read_csv(filename2)


In [ ]:
df.head()

Unnamed: 0  ... Pleural_Thickening
0           1  ...                0.0
1           2  ...                0.0
2           3  ...                0.0
3           4  ...                0.0
4           5  ...                0.0

[5 rows x 24 columns]

In [ ]:
df2.head()

Unnamed: 0              path  ...  Emphysema  Pleural_Thickening
0           1  00000001_001.png  ...        0.0                 0.0
1           2  00000001_002.png  ...        1.0                 0.0
2           3  00000002_000.png  ...        0.0                 0.0
3           4  00000003_001.png  ...        0.0                 0.0
4           5  00000003_002.png  ...        0.0                 0.0

[5 rows x 24 columns]

In [ ]:
df_final = pd.concat([df, df2]) #.reset_index()
df_final.describe()

Unnamed: 0     No Finding  ...      Emphysema  Pleural_Thickening
count  335534.000000  335534.000000  ...  335534.000000       335534.000000
mean    93112.837045       0.246598  ...       0.007498            0.010088
std     61713.975291       0.431031  ...       0.086269            0.099933
min         1.000000       0.000000  ...       0.000000            0.000000
25%     41942.250000       0.000000  ...       0.000000            0.000000
50%     83884.000000       0.000000  ...       0.000000            0.000000
75%    139530.750000       0.000000  ...       0.000000            0.000000
max    223414.000000       1.000000  ...       1.000000            1.000000

[8 rows x 23 columns]

In [ ]:
del df_final['Unnamed: 0']

In [ ]:
df_final.head()

path  ...  Pleural_Thickening
0  CheXpert-v1.0-small/train/patient00001/study1/...  ...                 0.0
1  CheXpert-v1.0-small/train/patient00002/study2/...  ...                 0.0
2  CheXpert-v1.0-small/train/patient00002/study1/...  ...                 0.0
3  CheXpert-v1.0-small/train/patient00002/study1/...  ...                 0.0
4  CheXpert-v1.0-small/train/patient00003/study1/...  ...                 0.0

[5 rows x 23 columns]

In [ ]:
df_final.to_csv('final_cheXpert_NIH.csv')

In [ ]:
df_final.describe()

No Finding  ...  Pleural_Thickening
count  335534.000000  ...       335534.000000
mean        0.246598  ...            0.010088
std         0.431031  ...            0.099933
min         0.000000  ...            0.000000
25%         0.000000  ...            0.000000
50%         0.000000  ...            0.000000
75%         0.000000  ...            0.000000
max         1.000000  ...            1.000000

[8 rows x 22 columns]

In [ ]:
valid  = df_final[-201:335533]

In [ ]:
valid.describe()

No Finding  Enlarged Cardiomediastinum  ...   Emphysema  Pleural_Thickening
count  200.000000                       200.0  ...  200.000000          200.000000
mean     0.640000                         0.0  ...    0.030000            0.015000
std      0.481205                         0.0  ...    0.171015            0.121857
min      0.000000                         0.0  ...    0.000000            0.000000
25%      0.000000                         0.0  ...    0.000000            0.000000
50%      1.000000                         0.0  ...    0.000000            0.000000
75%      1.000000                         0.0  ...    0.000000            0.000000
max      1.000000                         0.0  ...    1.000000            1.000000

[8 rows x 22 columns]

In [ ]:
valid.to_csv('final_NIH_valid.csv')

In [ ]:
a = 335533 - 200
print(a)

335333


In [ ]:
df_final_end = df_final[:335333]

In [ ]:
df_final_end.describe()

No Finding  ...  Pleural_Thickening
count  335333.000000  ...       335333.000000
mean        0.246361  ...            0.010085
std         0.430892  ...            0.099919
min         0.000000  ...            0.000000
25%         0.000000  ...            0.000000
50%         0.000000  ...            0.000000
75%         0.000000  ...            0.000000
max         1.000000  ...            1.000000

[8 rows x 22 columns]

In [ ]:
df_final_end.to_csv('final_cheXpert_NIH_train.csv')

In [ ]:
import random
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from PIL import Image

from torchvision import transforms

import torch
from torch.utils.data import Dataset

def getImagesLabels(filename):
    df = pd.read_csv(filename)

    relevant_cols = ['Path', 'No Finding', 'Enlarged Cardiomediastinum', 'Cardiomegaly' ,
                 'Lung Opacity', 'Lung Lesion', 'Edema',  'Consolidation',
                 'Pneumonia', 'Atelectasis' ,'Pneumothorax', 'Pleural Effusion',
                 'Pleural Other', 'Fracture', 'Support Devices']

    df = df[relevant_cols]
    df = df.replace(np.nan, 0.0)

    df = df.replace(-1.0, 2.0)


    X = df['Path']
    y = df[['No Finding', 'Enlarged Cardiomediastinum', 'Cardiomegaly' ,
                    'Lung Opacity', 'Lung Lesion', 'Edema',  'Consolidation',
                    'Pneumonia', 'Atelectasis' ,'Pneumothorax', 'Pleural Effusion',
                    'Pleural Other', 'Fracture', 'Support Devices']]
  
    return np.asarray(X), np.asarray(y)



In [ ]:
filename = '/content/drive/MyDrive/valid.csv'
x1, y1 = getImagesLabels(filename)
print(y1[0])

[0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
import numpy
val2 = [0,0,0,0,0,0,0,0]
val2 = [float(item) for item in val2]
val2 = numpy.array(val2)
#print(val2)
val3 = [0]*22
val3 = [float(item) for item in val3]
val3 = numpy.array(val3)
#print(val3)

for val in y1:
  val4 =np.append(val,val2)
  val3 = np.vstack([val3, val4])
  #np.vstack(dat_list)
  #val3 = numpy.append(val3, val4)
  
print(val3)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]


In [ ]:
DF = pd.DataFrame(val3)

In [ ]:
DF.head()

0    1    2    3    4    5    6   ...   15   16   17   18   19   20   21
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1  0.0  1.0  1.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4  0.0  1.0  0.0  1.0  0.0  1.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0

[5 rows x 22 columns]

In [ ]:
DF.columns = ['No Finding', 'Enlarged Cardiomediastinum', 'Cardiomegaly',
                    'Lung Opacity', 'Lung Lesion', 'Edema',  'Consolidation',
                    'Pneumonia', 'Atelectasis','Pneumothorax', 'Pleural Effusion',
                    'Pleural Other', 'Fracture', 'Support Devices','Hernia','Mass',
                    'Fibrosis','Infiltration','Effusion','Nodule','Emphysema','Pleural_Thickening']


In [ ]:
DF.head()

No Finding  Enlarged Cardiomediastinum  ...  Emphysema  Pleural_Thickening
0         0.0                         0.0  ...        0.0                 0.0
1         0.0                         1.0  ...        0.0                 0.0
2         0.0                         0.0  ...        0.0                 0.0
3         0.0                         0.0  ...        0.0                 0.0
4         0.0                         1.0  ...        0.0                 0.0

[5 rows x 22 columns]

In [ ]:
DF =DF.drop([0])

In [ ]:
DF.head()

No Finding  Enlarged Cardiomediastinum  ...  Emphysema  Pleural_Thickening
1         0.0                         1.0  ...        0.0                 0.0
2         0.0                         0.0  ...        0.0                 0.0
3         0.0                         0.0  ...        0.0                 0.0
4         0.0                         1.0  ...        0.0                 0.0
5         1.0                         0.0  ...        0.0                 0.0

[5 rows x 22 columns]

In [ ]:
DF.insert(0, 'path', x1)

In [ ]:
DF.head()

path  ...  Pleural_Thickening
1  CheXpert-v1.0-small/valid/patient64541/study1/...  ...                 0.0
2  CheXpert-v1.0-small/valid/patient64542/study1/...  ...                 0.0
3  CheXpert-v1.0-small/valid/patient64542/study1/...  ...                 0.0
4  CheXpert-v1.0-small/valid/patient64543/study1/...  ...                 0.0
5  CheXpert-v1.0-small/valid/patient64544/study1/...  ...                 0.0

[5 rows x 23 columns]

In [ ]:
#filename = '/content/y_label_names_path_data.csv'
#df = pd.read_csv(filename)
filename2 = '/content/final_NIH_valid.csv'
df2 = pd.read_csv(filename2)


In [ ]:
df_final = pd.concat([DF, df2]) #.reset_index()
df_final.describe()

No Finding  ...     Unnamed: 0
count  434.000000  ...     200.000000
mean     0.382488  ...  112018.500000
std      0.486556  ...      57.879185
min      0.000000  ...  111919.000000
25%      0.000000  ...  111968.750000
50%      0.000000  ...  112018.500000
75%      1.000000  ...  112068.250000
max      1.000000  ...  112118.000000

[8 rows x 23 columns]

In [ ]:
df_final.to_csv('final_cheXpert_NIH_valid.csv')

In [4]:
filename = '/content/drive/MyDrive/NIH_Dataset_total/final_cheXpert_NIH_train.csv'
df = pd.read_csv(filename)


In [5]:
df.head()

Unnamed: 0  ... Pleural_Thickening
0           0  ...                0.0
1           1  ...                0.0
2           2  ...                0.0
3           3  ...                0.0
4           4  ...                0.0

[5 rows x 24 columns]

In [29]:
#Es donde empieza el segundo path

path2 = 'images/'
print(df['path'][223414])

#for i, val in range(len(df['path'][223414 : ])):
#  print(val)
i = 0
for val in df['path'][223414 : ]:
  val2 = path2+val
  df['path'][223414 + i] = val2
  i = i +1


#print(j)  

00000001_001.png


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()


In [39]:
print(df['path'][223415])


images/00000001_002.png


In [41]:
df.to_csv('final_cheXpert_NIH_pthC_train.csv')

In [ ]:
!cp /content/drive/MyDrive/video_work_environment/sitting_standing_dataset_v3/train/standing_people -r /content/drive/MyDrive/video_work_environment/sitting_standing_dataset_v3/
